name: gir_yatra
description: Gir Yatra - Tourism Guide for Sasan Gir, Gujarat

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.0
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "gir_yatra_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A5C2A"
  adaptive_icon_foreground: "gir_yatra_icon_fg.png"
  web:
    generate: true
    image_path: "gir_yatra_icon.png"
    background_color: "#1A5C2A"
    theme_color: "#1A5C2A"

flutter_native_splash:
  color: "#1A5C2A"
  image: "gir_yatra_icon_fg.png"
  android_12:
    color: "#1A5C2A"
    image: "gir_yatra_icon_fg.png"
  android: true
  ios: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - gir_yatra_icon.svg
    - gir_yatra_icon.png
    - Image/Sasan Gir.jpg
    - Image/Devaliya Safari Park.jpg
    - Image/kankai mata.jpg
    - Image/Jamjir Waterfall.jpg
    - Image/Tulshi Shyam.jpg
    - Image/Veravel Beach.jpg
    - Image/Somnath Temple.jpg
    - Image/Girnar Hills.jpg
    - Image/Junagadh City.jpeg
    - Image/Diu Fort.jpg
